// Copyright (c) 2026, The Karbo developers
//
// This file is part of Karbo.
//
// KAT-based tests for the PQ Phase 1 domain-separated derivations (spec §6/§8).
// The pinned expected values are mirrored in tests/pq/kat_vectors.json — that
// file is the published artifact other implementations test against. A mismatch
// between independent implementations is a chain split (spec §14), so these
// vectors must never change once shipped.
//
// Fixed inputs are generated by pat<N>(a,b)[i] = (i*a + b) mod 256, documented
// alongside each vector in kat_vectors.json.

#include "gtest/gtest.h"

#include "crypto_pq/PqDerive.h"

#include <array>
#include <cstdint>
#include <cstring>
#include <string>
#include <vector>

using namespace CryptoPQ;

namespace {

std::string to_hex(const uint8_t* d, std::size_t n) {
    static const char* h = "0123456789abcdef";
    std::string o;
    o.reserve(2 * n);
    for (std::size_t i = 0; i < n; ++i) { o += h[d[i] >> 4]; o += h[d[i] & 0xf]; }
    return o;
}
template <std::size_t N> std::string to_hex(const std::array<uint8_t, N>& a) {
    return to_hex(a.data(), N);
}

// pat<N>(a,b)[i] = (i*a + b) mod 256 — deterministic filler for fixed inputs.
template <std::size_t N> std::array<uint8_t, N> pat(uint8_t a, uint8_t b) {
    std::array<uint8_t, N> r;
    for (std::size_t i = 0; i < N; ++i) r[i] = static_cast<uint8_t>(i * a + b);
    return r;
}

std::vector<InputRef> fixedInputs() {
    std::vector<InputRef> ins(2);
    ins[0].prevTxid = pat<32>(1, 0);   ins[0].prevOutIndex = 7;
    ins[1].prevTxid = pat<32>(255, 5); ins[1].prevOutIndex = 0x01020304;
    return ins;
}

}  // namespace

// ===========================================================================
// KAT vectors — must equal tests/pq/kat_vectors.json
// ===========================================================================

TEST(PqDerive, InputsHash) {
    EXPECT_EQ(to_hex(inputsHash(fixedInputs())),
              "05369b29b04c0150080312173ec816f49955043648896ac46d21c15860122400");
}

TEST(PqDerive, OutContext) {
    Hash256 ih = inputsHash(fixedInputs());
    KemCiphertext kemCt = pat<1088>(7, 3);
    EXPECT_EQ(to_hex(outContext(ih, kemCt, 1)),
              "2d8b4e207f8cd9b052e4ebd6e6a752b4a6f1363e52481a00445c8cec0a2f8615");
}

TEST(PqDerive, SpendSeed) {
    Hash256 ih = inputsHash(fixedInputs());
    Hash256 oc = outContext(ih, pat<1088>(7, 3), 1);
    KemShared ss = pat<32>(1, 0);
    EXPECT_EQ(to_hex(deriveSpendSeed(ss, oc)),
              "64f4dd994f27b62861feb57217a235cab9a05e2da32b9633f2b84317f507d671");
}

TEST(PqDerive, AeadKey) {
    Hash256 ih = inputsHash(fixedInputs());
    Hash256 oc = outContext(ih, pat<1088>(7, 3), 1);
    KemShared ss = pat<32>(1, 0);
    EXPECT_EQ(to_hex(deriveAeadKey(ss, oc)),
              "e93bdb04989a7a2833eea56830bb5d5091d2b4ecda8b0754a0abf8d69b0225c9");
}

TEST(PqDerive, SpendSeedAndAeadKeyDiffer) {
    // Same IKM + out_context, different info domain -> independent keys.
    Hash256 ih = inputsHash(fixedInputs());
    Hash256 oc = outContext(ih, pat<1088>(7, 3), 1);
    KemShared ss = pat<32>(1, 0);
    EXPECT_NE(deriveSpendSeed(ss, oc), deriveAeadKey(ss, oc));
}

TEST(PqDerive, SpendCommit) {
    DsaPublicKey pk = pat<1952>(5, 1);
    Rho rho = pat<32>(3, 9);
    EXPECT_EQ(to_hex(spendCommit(pk, rho)),
              "e68cb8c9336055b6627ca1a23f7b1a0962a2952d1f58466d28039c67405ca46d");
}

TEST(PqDerive, Nullifier) {
    DsaPublicKey pk = pat<1952>(5, 1);
    Rho rho = pat<32>(3, 9);
    EXPECT_EQ(to_hex(nullifier(pk, rho)),
              "93722da8561f4e172bdfc97d8abbde3ce29b09dc29c86fcb9edb550870c20869");
}

TEST(PqDerive, SpendCommitAndNullifierDiffer) {
    // Same (pk, rho), different domain -> distinct outputs.
    DsaPublicKey pk = pat<1952>(5, 1);
    Rho rho = pat<32>(3, 9);
    EXPECT_NE(spendCommit(pk, rho), nullifier(pk, rho));
}

TEST(PqDerive, TxSigningDigest) {
    DsaPublicKey pk = pat<1952>(5, 1);
    Rho rho = pat<32>(3, 9);
    Hash256 ih = inputsHash(fixedInputs());
    Hash256 oc = outContext(ih, pat<1088>(7, 3), 1);
    Hash256 sc = spendCommit(pk, rho);

    UnsignedTx tx;
    tx.version = 4;
    tx.fee = 12345;

    DigestInput di;
    di.prevTxid = pat<32>(1, 0);
    di.prevOutIndex = 7;
    di.authPub = pk;
    di.rhoReveal = rho;
    tx.inputs.push_back(di);

    DigestOutput out;
    out.type = 0x10;
    out.amount = 1000000;
    out.kemCt = pat<1088>(7, 3);
    out.encPayload = pat<48>(2, 1);
    out.spendCommit = sc;
    tx.outputs.push_back(out);

    EXPECT_EQ(to_hex(txSigningDigest(tx)),
              "586ee9aba67d7fdf5fa810a6daeda929fa86032db86eb4e248d47ecc21527722");
}

TEST(PqDerive, TxSigningDigestIsTamperSensitive) {
    DsaPublicKey pk = pat<1952>(5, 1);
    Rho rho = pat<32>(3, 9);

    UnsignedTx tx;
    tx.version = 4;
    tx.fee = 12345;
    DigestInput di; di.prevTxid = pat<32>(1, 0); di.prevOutIndex = 7;
    di.authPub = pk; di.rhoReveal = rho;
    tx.inputs.push_back(di);
    DigestOutput out; out.type = 0x10; out.amount = 1000000;
    out.kemCt = pat<1088>(7, 3); out.encPayload = pat<48>(2, 1);
    out.spendCommit = spendCommit(pk, rho);
    tx.outputs.push_back(out);

    Hash256 base = txSigningDigest(tx);

    UnsignedTx t2 = tx;
    t2.fee += 1;  // flip the fee
    EXPECT_NE(base, txSigningDigest(t2));

    UnsignedTx t3 = tx;
    t3.outputs[0].amount += 1;  // flip an output amount
    EXPECT_NE(base, txSigningDigest(t3));
}

// ===========================================================================
// Reserved-namespace guard (spec plan §2 item 8): no v4-plain derivation may
// reuse the Phase-2 KDSK-CT mask domain.
// ===========================================================================

TEST(PqDerive, ReservedCtMaskNamespaceUnused) {
    const std::string reserved = kReservedCtMask;
    const char* used[] = {
        kDomainInputsHash, kDomainOutContext, kDomainSpendSeed, kDomainAeadKey,
        kDomainSpendCommit, kDomainNullifier, kDomainTxSign,
    };
    for (const char* tag : used) {
        EXPECT_NE(std::string(tag), reserved);
    }
}

int main(int argc, char** argv) {
    ::testing::InitGoogleTest(&argc, argv);
    return RUN_ALL_TESTS();
}
